# Generated by Django 4.1.2 on 2022-10-15 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("disability_info", "0002_disabilityinfo_user_date_of_birth_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="disability_info",
        ),
        migrations.AddField(
            model_name="user",
            name="disability_description",
            field=models.TextField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="user",
            name="disability_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emergency_contacts",
                related_query_name="emergency_contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="DisabilityInfo",
        ),
    ]
