# Generated by Django 4.1.2 on 2022-10-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disability_info", "0003_remove_user_disability_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="disability_description",
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="disability_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
